name: php-cs-fixer

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs --allow-risky=yes

      - uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: Apply php-cs-fixer changes
